---
- hosts: all
  remote_user: root
  sudo: yes

  vars:
    cluster_name: Cassandra Cluster
    seeds: "159.203.15.91"
    document_root: /var/www/api.senseforage.com
    jupyter_root: /var/www/api.senseforage.com/jupyter

  roles:
    - common
    # - cassandra
    - mongodb
    - analytical
    - web
