---
- hosts: all
  remote_user: vagrant
  sudo: yes

  vars:
    document_root: /home/vagrant
    jupyter_root: /home/vagrant/jupyter
    cluster_name: Cassandra Cluster
    seeds: "127.0.0.1"

  roles:
    - common
    # - cassandra
    - mongodb
    - web
